=begin
#Switch Database REST API

#Switch API is the primary endpoint of data sevices and Switch DB's platform. You can do adding, editing, deleting or listing data works to your database with query operations by using this low-level API based on HTTP.

OpenAPI spec version: 1.2.1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AuthorizationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AuthorizationApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AuthorizationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuthorizationApi' do
    it 'should create an instact of AuthorizationApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AuthorizationApi)
    end
  end

  # unit tests for token_get
  # Generate Access Token
  # For generating Access Token, you need API Key and API Secret parameters that are provided from the developer portal. At the request, API Key that will be sent by using header is generated as portal API Key and Signature parameter is generated as md5(APISecret + ExpireTimestamp) format. At Expire parameter, token&#39;s expire date and time information must be proper to ISO 8601 standarts and Unix Time format with msec information. 
  # @param api_key Your Switch API Key.
  # @param signature Signature parameter is generated as md5(APISecret + ExpireTimestamp) format.
  # @param expire Expire parameter, token&#39;s expire date and time information must be proper to ISO 8601 standarts and Unix Time format with msec information.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'token_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
